### ISSUE TITLE
README file isn't in main directory

### ISSUE THREAD

**Issue by ExcaliburZero** [cdqwertz/rooms#2]
Currently the README file for the mod is located in the "mpgen" sub-directory. However, this is probably not the best place for it.

Since most modpacks include the main README file in the main directory, people are more likely to look for it there, rather than in one of the sub-directories.

Thus, the README.md file in the mpgen sub-directory should probably be moved into the main directory of the modpack, so that it is easier to find.

**Comment by HybridDog** [comment]
you could also make a recursive symbolic link

**Comment by cdqwertz** [comment]
ok, fixed :D
